### ISSUE TITLE
Milestone: Wrappers Showcase

### ISSUE THREAD

**Issue by rihp** [polywrap/landing-page#90]
This is a "marketing" or "hero showcase" of the wrappers that are currently featured. The wrappers cycle and fade to show various queries.

Here's something similar what it'd look like:
![image](https://user-images.githubusercontent.com/12145726/170373785-e3a51ce3-39f5-4a65-954f-c8c77b39f844.png)

## Next steps 

- [x] Display the new card with the function names
- [x] Enable cms functionality in the function card
- [ ] IDE should be able to do syntax highlighting for Rust, Go, and Python too
- [x] Add pocket network directly from testimonial
- [x] Specify which wrappers we want to feature and update their data. Candidates are below:
   - [x] Defiwrapper
   - [x] Univ3

### React IDE Component

- [x] Finishing #105 and
- [x] Refactor components so the code is clean and production ready, without many duplications
- [x] This ties back to  https://github.com/polywrap/hub/issues/216

**Comment by rihp** [comment]
Probably modify this section
![image](https://user-images.githubusercontent.com/12145726/154847333-f1d89a79-39de-4c88-b616-fade8931e228.png)

- [component](https://github.com/polywrap/landing-page/blob/master/src/components/Testimonials.tsx) 
- [copy](https://github.com/polywrap/landing-page/blob/master/src/constants/launch-partners.ts)

**Comment by rihp** [comment]
The Tezos wrapper by blockwatch is a great usecase with appropriate documentation. It shows both DeFi and an NFT usecase.

While still under development, it enables a lot in the TZ ecosys

![image](https://user-images.githubusercontent.com/12145726/155397426-95f92870-8c6a-4aa3-af89-9bbeef49267e.png)
https://blockwatch.gitbook.io/polywrap-tezos/using-polywrap/tezos-domains-wrapper

**Comment by rihp** [comment]
We're considering using a Headless CMS to feed the copy to the landingpage.

Eugene has recommended looking into Contentful as an option.
[Here](https://hackmd.io/@eugenefine/SktQ9B-gq) are some notes from our most recent discussion

**Comment by rihp** [comment]
Colin suggests either Contenful or Netlify as options for the headless cms

**Comment by rihp** [comment]
Was thinking of using code snippets that would populate a IDE / mocked code editor and showcase an insightful function, along with a description and name/title for the showcase

This is what the graph is doing today. It's their first section after a user scrolls down on their page.
They show 3 Gifs of their Subgraph Explorer executing a query, while the text on the right is static.
![image](https://user-images.githubusercontent.com/12145726/155522861-e3b2a3ea-7615-4bfb-9053-923d232dce74.png)

**Comment by rihp** [comment]
Using contentful, we can use this query on it GraphQL API, 
```graphql
{ featuredWrapper(id: "4ZejFLXPkd2Il1qRAtePLw") {
  wrapperName
  clientInput
  wrapperOutput
  wrapperDescription
  docsLink
  featured
  thirdParty
  }
}
```

and resolve this result which can be then plugged into a frontend component
```json
{
  "data": {
    "featuredWrapper": {
      "wrapperName": "Tezos Polywrapper",
      "clientInput": "const uri = 'w3://ens/tezos-domains.web3api.eth'\nexport const resolveDomainRecords = async (connection, domain) => {\n    return client.query({\n        uri,\n        query: \n        `query {\n\t    resolveDomainRecords(connection: $connection, domain: \"${domain}\" )\n        }`,\n        variables: {\n            connection\n        }\n    })\n}",
      "wrapperOutput": "{\n  json; response,\n  goes: here,\n  with:\n    {\n      query: response\n     }\n}",
      "wrapperDescription": "This project lead by BlockWatch is allows any developer to connect to the Tezos blockchain, as well as query its native protocols like Hic et Nunc for NFTs and Tezos Name Service.",
      "docsLink": "https://blockwatch.gitbook.io/polywrap-tezos/",
      "featured": true,
      "thirdParty": true
    }
  }
}

```

**Comment by rihp** [comment]
To fetch Hero section content use this query:

```
{ webContent(id: "6DWrAojZUdPcTSDXGip5PN") {
  title
  subtitle
  description
  callToAction
}

}
```
currently the output structure for web content elements looks like
```
{
  "data": {
    "webContent": {
      "title": "Use Web3 Anywhere.",
      "subtitle": "PRE-ALPHA",
      "description": "Polywrap is a development platform that enables easy integration of Web3 protocols into any application. It makes it possible for software on any device, written in any language, to read and write data to Web3 protocols",
      "callToAction": "JOIN OUR DISCORD"
    }
  }
}
```

**Comment by rihp** [comment]
started implementing the cms here https://github.com/polywrap/landing-page/tree/contentful-dev
might have to create a new issue just to track CMS integration

**Comment by rihp** [comment]
Contenful implementation is almost finished, so we are about to be ready to integrate the new Wrapper Showcase component. This would look like this :

- [Link to component](https://github.com/polywrap/landing-page/blob/master/src/components/IDE.tsx)
![image](https://user-images.githubusercontent.com/12145726/161775930-3eaab4fe-8816-4f23-9df0-e116c8f77bbf.png)

**Comment by rihp** [comment]
This is what the section looks now
<img width="1409" alt="image" src="https://user-images.githubusercontent.com/12145726/161838492-955d4022-826c-473a-82b9-93361d7b6f0c.png">

- [ ] Define what to show in these queries
- [ ] What tabs should the reader have to check ? Query graphql, and variables.json ?

**Comment by dOrgJelli** [comment]
Some quick feedback:
- simplestorage.ts is confusing IMO, I think just typing `app.ts` would be easier.
- Would recommend changing the code snippet to a rotating set of examples, to help show how easy it is to integrate different wrappers. Here are a few options:
```typescript
// Execute Token Swaps w/ Uniswap V3
client.invoke({
  uri: "wrap://ens/v3.uniswap.polywrap.eth",
  module: "mutation",
  method: "swap",
  input: {
    inToken,
    outToken,
    amount,
    ...
  }
});
```
source: https://github.com/polywrap/integrations/blob/2282781a2ba46ef99c41f093b9985487c8a1e98e/uniswapv3/wrapper/src/mutation/schema.graphql#L46-L61

```typescript
// Compute Trade Outputs w/ Uniswap V3
client.invoke({
  uri: "wrap://ens/v3.uniswap.polywrap.eth",
  module: "query",
  method: "bestTradeExactIn",
  input: {
    pools,
    amountIn,
    tokenOut,
    ...
  }
});
```
source: https://github.com/polywrap/integrations/blob/2282781a2ba46ef99c41f093b9985487c8a1e98e/uniswapv3/wrapper/src/query/schema.graphql#L470-L479

```typescript
// Fetch P2P Data w/ IPFS
client.invoke({
  uri: "wrap://ens/ipfs.polywrap.eth",
  module: "query",
  method: "catFile",
  input: {
    cid,
    options
  }
});
```
source: https://github.com/polywrap/monorepo/blob/03ca9d2f0cbe931762cbd15739cd50ac1f21d1bb/packages/js/plugins/ipfs/schema.graphql#L4-L7

```typescript
// Resolve Addresses w/ ENS Domains
client.invoke({
  uri: "wrap://ens/ens.polywrap.eth",
  module: "query",
  method: "getAddress",
  input: {
    domain,
    resolverAddress,
    ...
  }
});
```
source: https://github.com/polywrap/integrations/blob/faf7670fa0f6227c129b7765de613910bea973fa/ens/wrapper/src/query/schema.graphql#L18-L22

```typescript
// Set Text Records on ENS Domains
client.invoke({
  uri: "wrap://ens/ens.polywrap.eth",
  module: "mutation,
  method: "setTextRecord",
  input: {
    domain,
    resolverAddress,
    key,
    value,
    ...
  }
});
```
source: https://github.com/polywrap/integrations/blob/faf7670fa0f6227c129b7765de613910bea973fa/ens/wrapper/src/mutation/schema.graphql#L138-L145

NOTE: the `polywrap.eth` domain has not been configured to host these wrappers yet, but will be post alpha-launch

**Comment by dOrgJelli** [comment]
additionally, in order to drive home the "multi-platform" benefit, we could have tabs named: `app.ts`, `app.js`, `app.py`, `app.rs`, `app.go`

And the code snippet could stay mostly the same, showing that the developer experience is the same throughout.

**Comment by evanjacobs** [comment]
I like the idea of rotating between examples to show the breadth of possibilities. I also think the comment line at the top of each example really helps to quickly provide context about what the code is doing.

**Comment by rihp** [comment]
Awesome, will work on this rotating implementation, with the various tabs, and a link to source

From today's defiwrapper call, we can showcase these functions : 
 - account resolver to check an account's balance 
 - specific protocol resolver
 - price request with coin gecko

**Comment by dOrgJelli** [comment]
Amazing, let's add them to the ever growing list @rihp!!!

**Comment by rihp** [comment]
Ok, starting to set up the content in CMS before we query it from the FE
are we certain that we want to show each tab as a different language?  @dOrgJelli is there any other alternative we have to consider ?

**Comment by rihp** [comment]
Started implementing the IDE here, with the data being fetched from our CMS.

Next steps 
- [ ] Get the data from all featured wrappers
- [ ] Specify what languages would be on each tab, and what the client implementation would look like for each language @dOrgJelli @codentell would you be able to give me a guide ?
- [ ] Add defiwrapper queries to CMS
- [ ] Refactor components so the code is clean and production ready, without many duplications

https://github.com/polywrap/landing-page/compare/3d43186098df...83700f1a5989

**Comment by rihp** [comment]
@MuathJ has been helping me implement the IDE syntax highlights and the carrousel/rotating code snipets animation 

some progress here
https://github.com/polywrap/landing-page/tree/lp-code-carousel

**Comment by rihp** [comment]
This query would fetch all necessary data to populate the IDE components, and its periphery 
```
query { 
    featuredWrapper(id: "1Lo0Gmtk7BI5v0bNmzPRhb") { 
      wrapperName
      description
      featured
      thirdParty
      queriesCollection {
        items {
          filename
          featured
          appTs
          appRs
          appPy
          source
        }
      }  
    docsLink
    }
  } 
```

**Comment by rihp** [comment]
more progress on https://github.com/rihp/polywrap-landing-page/pull/5

this can query data from the CMS, map it to the IDE component, and uses the mocked "function Card" hovering on top of the IDE to list the different functs of the wrapper 

this is what it looks like rn
![image](https://user-images.githubusercontent.com/12145726/170360981-b961bc37-7862-4f29-839d-24c6d594831c.png)

**Comment by rihp** [comment]
see it on fleek : https://broken-cake-0397.on.fleek.co/#/

**Comment by rihp** [comment]
After a chat with Jordan I have fixed this PR ( #146  ) in order to remove the CMS integration, and still use the improved data structures. 

@kev-ngo has mentioned he'd take a final look before merging, but it should be ready.

**Comment by rihp** [comment]
merged, finally!
